購入履歴と購入詳細ページを作成しました
yusaymmt/lamp_practice pull request #15
Opened 2020-04-20 14:30 UTC by yusaymmt

購入履歴と購入詳細ページを追加しました。
購入詳細ページでは、item_idとhistory_idを使って２つのテーブルから必要な情報を一度に受け取ることが出来るのではないかと考えましたが、SQL文が上手く通りません…
何かいいアドバイスはありますでしょうか？

2020-04-20 15:30 UTC, primestyleus requested changes
全体の流れとしてはよい形にできていると思います。ただ、1度に2商品以上購入した場合に明細画面が正しく機能しないと思いますので、まずはそこを修正いただければと思います。注文の合計金額については、SUMやGROUP BYなどをうまく組み合わせてMySQL側で計算させるときれいにできます。一覧画面から明細画面に遷移するときに必要なのはhistory_idだけでよいはずですので、そこも考えてみてください。

2020-04-20 15:36 UTC, primestyleus commented
以下のSQLですが、whereからitem_idの条件をなくせば通るかと思いますが、いかがでしょうか？
`SELECT history_detail.created,
    history_detail.amount,
    history_detail.price,
    items.name
FROM history_detail
JOIN items
ON history_detail.item_id = items.item_id
WHERE item_id = :item_id AND history_id = :history_id`

2020-04-21 02:39 UTC, yusaymmt commented
コメントに基づき、購入明細ページと訂正しました。
再度確認お願いします。

2020-04-21 06:41 UTC, primestyleus requested changes
複数商品を購入したときに、一覧画面に同じ注文番号で複数のレコードが出てきてしまいます。
https://gyazo.com/237e2b93855b65cee9f54921446c92e2
上記の例ですと、注文番号1については1行だけで合計が130,000と表示されるのが、正しい動きとなります。

また、こちらは前回の課題での確認漏れだったので、申し訳ないのですが、購入日時が正しく保存されずにNULLが入ってしまうようですので、こちらについても合わせて修正をお願いします。

2020-04-21 06:41 UTC, primestyleus commented on www/model/history.php
> +function get_history($db, $user_id) {
このメソッドは、履歴一覧の画面で使われているものですので、detailテーブルとの連携は必要ですが、取得するデータとしては、注文番号、購入日時、合計（こちらは計算式が必要）の3項目のみでよいかと思います。

2020-04-21 06:41 UTC, primestyleus commented on www/model/history.php
> +  $sql = "SELECT SUM(price * amount)
SUM(price * amount) の計算は完璧です！できれば'AS subtotal'のようにASを利用すると、viewで実際に使うときの記述がわかりやすくなります。（必須の修正ではありません）

2020-04-21 15:04 UTC, yusaymmt commented
購入履歴画面を修正しましたので確認お願いします！

2020-04-21 15:52 UTC, primestyleus approved these changes
「課題2・追加テーブルへのデータ保存」の部分でうまくいっていない部分がいくつかありました。バグ修正ということで、こちらから課題を立てたいと思います。いったんこちらはマージしたいと思います。おつかれさまでした！

2020-04-21 23:02 UTC, closed without merging