並び替え機能を実装しました
yusaymmt/lamp_practice pull request #21
Opened 2020-04-23 07:19 UTC by yusaymmt

問題点が少なくとも2点ありますが、一度見ていただきたくプルリクエストを送らせていただきました！
まず、並び替えのプルダウンメニューをcssで画面右寄せにしようとしましたが、上手くいきません。
2点目はこの課題ではないのですが、並び替えがきちんと出来ているか動作確認をする際に商品を追加しようとしましたが、どうもadmin_insert_item.phpが上手く動いてくれず、商品追加が出来ません…
ので、一度確認していただき、アドバイスを頂けたらと思います、お願いします！

2020-04-23 14:16 UTC, primestyleus commented
@yusaymmt 
こちら確認しました。こちらで見る限り、CSSはきちんと反映できているようです。以下について修正してみてください。

・view/admin_view.phpの48行目、printが抜けているためうまくtokenが設定できていないようです。
・html/admin_insert_item.phpの40行目、redirect_to(ADMIN_URL)がelseの中にあるため、CSRF認証に失敗するとリダイレクトが行われず、画面に何も表示されない状態となっています

2020-04-24 00:52 UTC, yusaymmt commented
商品追加できなかった点、先生のおかげで解決しました！ありがとうございました！
商品並び替えに関して、動作確認ができましたので、再度確認をお願いします！

2020-04-24 03:38 UTC, primestyleus requested changes
動作としては問題ないのですが、一部記述が冗長な部分があるので、修正いただけますでしょうか？よろしくお願いいたします。

2020-04-24 03:38 UTC, primestyleus commented on www/html/index_sort_items.php
> +//sortが１の時(新着順)
似た処理の関数が続いているので、できれば get_items_by($db, $sort)と呼べるようなモデル（関数）の設計にするとコードもすっきりするかと思います。

2020-04-24 06:28 UTC, yusaymmt commented
get_items_by関数を作成してコントローラーをスッキリさせることが出来ました！

2020-04-24 06:45 UTC, primestyleus requested changes
@yusaymmt コントローラについては良いですね！

少し説明不足で申し訳ないのですが、以下のモデルの3つの関数の記述がほぼ同じです。

sort_by_newest, sort_by_lowest, sort_by_highest

ORDER BYに続く部分が違うだけなので、そこだけをうまくif/elseで切り替えられるのが理想です。ちょっと5章に出てくるDRYの原則にも関係した考え方となります。

get_items_byの中で、SQLも定義し、$sortの値によってORDER BYの内容を切り分ける、とできると、作る関数も減ってスッキリします。もう1回考えてみていただけますか？

2020-04-26 03:37 UTC, yusaymmt commented
$sortによってSQLの文末が変更するように、関数化してみましたので確認お願いします！

2020-04-26 04:41 UTC, primestyleus commented
index_sort_items.phpは作らずindex.phpに追記でもいいと思いますが、いったんこちらでマージします。

2020-04-26 04:41 UTC, merged