購入履歴を保存するテーブルの作成
yusaymmt/lamp_practice pull request #9
Opened 2020-04-16 08:30 UTC by yusaymmt

テーブルを作成するSQL文を作成したので確認お願いします。

2020-04-17 14:43 UTC, primestyleus requested changes
必要な項目としては網羅されていますね！ただ、一つの注文で複数の商品を購入できるのですが、テーブルが一つだとそのケースに対応することができません。複数のテーブルが必要となります。

2020-04-18 03:36 UTC, primestyleus requested changes
historyとhistory_detailの関係はこちらでOKです！正規化の考えのひとつに計算できるものはテーブルに含めない、というものがありますので、historyテーブルにはtotalを含めないほうがいいかと思います。(subtotalの合計で求まるため)　また、subtotalについても商品価格から求めるという考えもありますが、ここは注意が必要です。一般的にECサイトでは値段は変動するため、購入時のアイテムの値段を履歴に一緒に残すか、もしくは小計だけを残す必要があります。そういった意味では、subtotalがここにあるのは問題ないと思います。

2020-04-18 05:27 UTC, yusaymmt commented
totalを消してsubtotalを残す理由、納得しました！
テーブルからtotalを削除しましたので確認お願いします。
（前の課題のトークンの名前の編集も一緒にしました）

2020-04-18 11:47 UTC, primestyleus commented
@yusaymmt 
申し訳有りません、ちょっと私の指示が間違っておりました。詳細画面で「購入時の商品価格」を表示するため、価格を詳細テーブルに保存していただき、subtotalは計算で算出するのがベストです。何度もすみません！

2020-04-18 11:59 UTC, yusaymmt commented
テーブル更新しなおしました！
確かに前回コメントをよく考えれば、購入時の価格と数量さえ保存していればsubtotalも不必要なことが考えられました…
計算できるものはテーブルに含めない、これからも気を付けていきます！
再度確認お願いします。

2020-04-18 12:01 UTC, primestyleus approved these changes

2020-04-18 12:01 UTC, merged